<center><img src="grand_slam.jpg"/></center>

<h1><center>Predicting Tennis Match Results</center></h1>

## Introduction

On May 8, 2022, Carlos Alcaraz, 19 year old Spanish professional tennis player, defeated World Number 1 Novak Djokovic in a 3-set thriller at the Madrid Open. Looking at the statistics of the match, the most surprising statistic was that Alcaraz won 100% of his second serves. To someone unfamiliar with tennis terminology, this may not mean all that much. Refer to the following link for a comprenhensive list of tennis terms: https://en.wikipedia.org/wiki/Glossary_of_tennis_terms. There are four main grand slam tennis tournaments yearly which are namely Australian Open, French Open, Wimbledon, and US Open. These four grand slam tournaments are the most famous tennis tournaments all over the world. Needless to say, the court surfaces of these mega tennis events are also different. Australian and US Open are to be played on hard courts, French Open is to be played on
clay courts and Wimbledon is to be played on grass courts. Every court surface has its own features and creates
variations in bounce and speed of the ball. Clay courts produce gentler paced ball and an equally accurate bounce
with extra spin. Hard courts produce faster paced ball and very accurate bounces. Grass courts produce faster ball
movements with added unpredictable types of bounces. Furthermore, the scoring systems of men’s and women’s
singles matches in grand slam tournaments are also different. Typically, in men’s matches, a player who wins three
sets out of five sets wins the match. Whereas, in the women’s matches, the first player winning two sets out of three
sets wins the match.

With Madrid Open underway leading up to the French Open, coaching staff, new agencies, and spectators are beginning to talk about winner predictions. With technological advancements, these prediction models evaluate a player's chances of winning matches, but developing these models is a difficult task given so many unpredictable variables. The goal of this project is to predict the outcome of tennis sinlges matches using match statistics of 2013 Grand Slam Tournaments.

## Data Collection

The datasets used for this project were from the UCI Machine Learning Repository. Link to the datasets is here: https://archive.ics.uci.edu/ml/datasets/Tennis+Major+Tournament+Match+Statistics

There were 8 datasets total, one per Grand Slam and Gender. Each row of the data represents one match played in the tournament and includes a variety of numerial factors about the match. All of the variables listed below are collected for both players, represented in the dataset with a ".1" or ".2" for Player1 and Player2, respectively. For example, FSP.1 is the First Serve Percentage for Player 1 and FSP.2 is the First Serve Percentage for Player 2.

| Attibute | Desciption |
| :- | :- |
| Player1 | Name of Player 1|
| Player2 | Name of Player 2|
| Result | 1 if Player 1 wins, 0 otherwise |
| FSP | First serve % |
| FSW | Win % on 1st serve |
| SSP | Second serve % |
| SSW | Win % on 2nd serve |
| ACE | Aces won |
| DBF | Double faults commited|
| WNR | Winners hit|
| UFE | Unforced error commited |
| BPC | Break points created|
| BPW | Break points won |
| NPA | Net points attempted|
| NPW | Net points won |
| TPW | Total points won |
| ST1 | Games won in set 1 |
| ST2 | Games won in set 2 |
| ST3 | Games won in set 3 |
| ST4 | Games won in set 4 |
| ST5 | Games won in set 5 |
| FNL | Final number of sets wons |
| Round | Round of the tournamnet at which game is played

In [1]:
import pandas as pd
import numpy as np
import re

In [88]:
# create dataframe for Australian Open
aus_open_men = pd.read_table("AusOpen-men-2013.csv", sep=",")
aus_open_men.name = "aus_open_men"
aus_open_women = pd.read_table("AusOpen-women-2013.csv", sep=",")
aus_open_women.name = "aus_open_women"

# create dataframe for French Open
french_open_men = pd.read_table("FrenchOpen-men-2013.csv", sep=",")
french_open_men.name = "french_open_men"
french_open_women = pd.read_table("FrenchOpen-women-2013.csv", sep=",")
french_open_women.name = "french_open_women"

# create dataframe for Wimbledon
wimbledon_men = pd.read_table("Wimbledon-men-2013.csv", sep=",")
wimbledon_men.name = "wimbledon_men"
wimbledon_women = pd.read_table("Wimbledon-women-2013.csv", sep=",")
wimbledon_women.name = "wimbledon_women"

# create dataframe for US Open
us_open_men = pd.read_table("USOpen-men-2013.csv", sep=",")
us_open_men.name = "us_open_men"
us_open_women = pd.read_table("USOpen-women-2013.csv", sep=",")
us_open_women.name = "us_open_women"

us_open_women

,Player 1,Player 2,ROUND,Result,FNL.1,FNL.2,FSP.1,FSW.1,SSP.1,SSW.1,...,BPC.2,BPW.2,NPA.2,NPW.2,TPW.2,ST2.1.1,ST2.2,ST3.2,ST4.2,ST5.2
0,S Williams,V Azarenka,7,1,2,1,57,44,43,20,...,8,4,15.0,10.0,NaN,5,7,1.0,NaN,NaN
1,F Pennetta,V Azarenka,6,0,0,2,44,12,56,7,...,13,8,30.0,20.0,NaN,6,6,NaN,NaN,NaN
2,S Williams,N Li,6,1,2,0,63,26,37,9,...,4,1,19.0,13.0,NaN,0,3,NaN,NaN,NaN
3,R Vinci,F Pennetta,5,0,0,2,60,21,40,7,...,12,6,14.0,7.0,NaN,6,6,NaN,NaN,NaN
4,D Hantuchova,V Azarenka,5,0,0,2,58,14,42,5,...,11,7,13.0,12.0,NaN,6,6,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,P Ormaechea,K Date-Krumm,1,1,2,0,59,32,41,10,...,9,4,14.0,9.0,NaN,3,6,NaN,NaN,NaN
72,K Pliskova,E Bouchard,1,0,1,2,53,48,47,21,...,13,3,13.0,10.0,NaN,4,6,7.0,NaN,NaN
73,L Hradecka,A Kerber,1,0,0,2,49,17,51,4,...,8,5,6.0,5.0,NaN,6,6,NaN,NaN,NaN
74,L Davis,C Suarez Navarro,1,0,0,2,63,12,37,3,...,12,6,10.0,8.0,NaN,6,6,NaN,NaN,NaN
75,K Mladenovic,A Medina Garrigues,1,1,2,1,51,29,49,15,...,13,4,14.0,7.0,NaN,1,6,1.0,NaN,NaN

In [89]:
# list of all datasets as dataframes
data_frames = [aus_open_men, aus_open_women, french_open_men, french_open_women, \
               wimbledon_men, wimbledon_women, us_open_men, us_open_women]

# check the number of columns and rows:
for df in data_frames:
    print(df.name + ": " + str(len(df.columns)) + " attributes, " + str(len(df.index)) + " instances")

aus_open_men: 42 attributes, 126 instances
aus_open_women: 42 attributes, 127 instances
french_open_men: 42 attributes, 125 instances
french_open_women: 42 attributes, 127 instances
wimbledon_men: 42 attributes, 114 instances
wimbledon_women: 42 attributes, 122 instances
us_open_men: 42 attributes, 126 instances
us_open_women: 42 attributes, 76 instances

We can see that the number of attributes is the same, but the number of matches played varys for each Grand Slam. Now we are going to standardize all of the column names using the notation described above.

In [90]:
# list of grand slams to be added as column
grand_slam = ["AusOpen", "FrenchOpen", "Wimbledon", "USOpen"]

# variable that switches between "men" and "women"
gender = "men"

# standardized column names
columns = wimbledon_men.columns
pos = 0

# compare column names with standardized one above
for df in data_frames:
    # for each column name in df
    for i in range(len(df.columns)): 
        # If not like contol name 
        if df.columns[i] != columns[i]:
            wrong_name = df.columns[i]
            # Replace by the correct name
            df.rename(columns = {str(df.columns[i]): str(columns[i])}, inplace = True) 
            print(df.name + ": The following label", wrong_name,"was changed for", df.columns[i])
    
    # add additional info as columns in dataframe        
    df["Gender"] = gender
    df["GrandSlam"] = grand_slam[pos//2]
    gender = "women" if gender == "men" else "men"
    pos += 1

aus_open_men: The following label FNL1 was changed for FNL.1
aus_open_men: The following label FNL2 was changed for FNL.2
aus_open_women: The following label FNL1 was changed for FNL.1
aus_open_women: The following label FNL2 was changed for FNL.2
wimbledon_women: The following label ST1.1.1 was changed for ST1.2
us_open_men: The following label FNL1 was changed for FNL.1
us_open_men: The following label FNL2 was changed for FNL.2
us_open_women: The following label Player 1 was changed for Player1
us_open_women: The following label Player 2 was changed for Player2
us_open_women: The following label ROUND was changed for Round
us_open_women: The following label ST2.1.1 was changed for ST1.2

In [91]:
# merge it in one unique dataframe
gs_matches = pd.concat(data_frames, ignore_index = True)

gs_matches.isna().sum()

Player1        0
Player2        0
Round          0
Result         0
FNL.1          1
FNL.2          1
FSP.1          0
FSW.1          0
SSP.1          0
SSW.1          0
ACE.1         22
DBF.1          8
WNR.1        126
UFE.1        126
BPC.1          1
BPW.1          1
NPA.1         84
NPW.1         83
TPW.1        312
ST1.1          1
ST2.1          4
ST3.1        321
ST4.1        722
ST5.1        857
FSP.2          0
FSW.2          0
SSP.2          0
SSW.2          0
ACE.2         22
DBF.2          8
WNR.2        126
UFE.2        126
BPC.2          1
BPW.2          1
NPA.2         84
NPW.2         83
TPW.2        312
ST1.2          1
ST2.2          4
ST3.2        321
ST4.2        722
ST5.2        857
Gender         0
GrandSlam      0
dtype: int64

Combining all 8 dataseets into one large dataframe allows to have all match information in one place. The extra columns of "Gender" and "GrandSlam" provide a way to differentiate between each event.

## Data Processing

### Match Retirements

It is not uncommon that players do not finish a match, often due to injuries. This would lead to incomplete match statistics and do not provide a true representation of a player's performance in relation to their win. If a men's match was played to completions, either Player 1 or Player 2 would have won 3 sets, which would be in "FNL.X". Similar idea of women's matches except it would be 2 sets won. These conditions and missing values are tested below.

In [92]:
# list of matches that did not finish
incomplete = []
# check for unfinished matches, different criteria for each gender
for index, row in gs_matches.iterrows():
    if np.isnan(row["FNL.1"]) or np.isnan(row["FNL.2"]):
        incomplete.append(index)
    elif row["Gender"] == "men" and row["FNL.1"] != 3 and row["FNL.2"] != 3:
            incomplete.append(index)
    elif row["Gender"] == "women"  and row["FNL.1"] != 2 and row["FNL.2"] != 2:
            incomplete.append(index)
        
print(incomplete)
        
print(gs_matches.loc[[15]])

[7, 15, 24, 33, 38, 40, 63, 78, 170, 272, 288, 291, 295, 296, 299, 312, 344, 454, 455, 575, 590, 716, 748, 777, 806]
               Player1         Player2  Round  Result  FNL.1  FNL.2  FSP.1  \
15  Stanislas Wawrinka  Andrey Golubev      1       1    2.0    0.0     63

    FSW.1  SSP.1  SSW.1  ...  NPA.2  NPW.2  TPW.2  ST1.2  ST2.2  ST3.2  ST4.2  \
15     20     37      6  ...    6.0   12.0   37.0    4.0    1.0    NaN    NaN

    ST5.2  Gender  GrandSlam
15    NaN     men    AusOpen

[1 rows x 44 columns]

Of the 943 matches, 25 do not have complete match statistics. The information for one such match that did not finish is displayed. According to a Sportsnet article, Andrey Golubev retired with an injured left leg from the 2013 Australian Open match against Stanislas Wawrinka after just 15 games.

In [93]:
# remove matches that did not finish
gs_matches.drop(incomplete, inplace=True)
gs_matches.reset_index(inplace=True, drop=True)

gs_matches

,Player1,Player2,Round,Result,FNL.1,FNL.2,FSP.1,FSW.1,SSP.1,SSW.1,...,NPA.2,NPW.2,TPW.2,ST1.2,ST2.2,ST3.2,ST4.2,ST5.2,Gender,GrandSlam
0,Lukas Lacko,Novak Djokovic,1,0,0.0,3.0,61,35,39,18,...,8.0,9.0,101.0,6.0,7.0,6.0,NaN,NaN,men,AusOpen
1,Leonardo Mayer,Albert Montanes,1,1,3.0,0.0,61,31,39,13,...,NaN,NaN,42.0,1.0,3.0,1.0,NaN,NaN,men,AusOpen
2,Marcos Baghdatis,Denis Istomin,1,0,0.0,3.0,52,53,48,20,...,12.0,16.0,126.0,6.0,7.0,6.0,NaN,NaN,men,AusOpen
3,Dmitry Tursunov,Michael Russell,1,1,3.0,0.0,53,39,47,24,...,NaN,NaN,79.0,2.0,2.0,3.0,NaN,NaN,men,AusOpen
4,Juan Monaco,Ernests Gulbis,1,0,1.0,3.0,76,63,24,12,...,16.0,28.0,127.0,1.0,6.0,7.0,6.0,NaN,men,AusOpen
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,P Ormaechea,K Date-Krumm,1,1,2.0,0.0,59,32,41,10,...,14.0,9.0,NaN,3.0,6.0,NaN,NaN,NaN,women,USOpen
914,K Pliskova,E Bouchard,1,0,1.0,2.0,53,48,47,21,...,13.0,10.0,NaN,4.0,6.0,7.0,NaN,NaN,women,USOpen
915,L Hradecka,A Kerber,1,0,0.0,2.0,49,17,51,4,...,6.0,5.0,NaN,6.0,6.0,NaN,NaN,NaN,women,USOpen
916,L Davis,C Suarez Navarro,1,0,0.0,2.0,63,12,37,3,...,10.0,8.0,NaN,6.0,6.0,NaN,NaN,NaN,women,USOpen
917,K Mladenovic,A Medina Garrigues,1,1,2.0,1.0,51,29,49,15,...,14.0,7.0,NaN,1.0,6.0,1.0,NaN,NaN,women,USOpen

There are 918 matches that played to completion. We now turn out attention to missing values and imputing data.

### Missing Values and Imputation

In [94]:
# print the number of NAs in our dataset per variable
gs_matches.isna().sum()

Player1        0
Player2        0
Round          0
Result         0
FNL.1          0
FNL.2          0
FSP.1          0
FSW.1          0
SSP.1          0
SSW.1          0
ACE.1         22
DBF.1          6
WNR.1        123
UFE.1        123
BPC.1          0
BPW.1          0
NPA.1         83
NPW.1         82
TPW.1        309
ST1.1          0
ST2.1          0
ST3.1        309
ST4.1        701
ST5.1        832
FSP.2          0
FSW.2          0
SSP.2          0
SSW.2          0
ACE.2         22
DBF.2          6
WNR.2        123
UFE.2        123
BPC.2          0
BPW.2          0
NPA.2         83
NPW.2         82
TPW.2        309
ST1.2          0
ST2.2          0
ST3.2        309
ST4.2        701
ST5.2        832
Gender         0
GrandSlam      0
dtype: int64

#### Aces NaN

From the summary of missing values above, it is curious that ACE.1 and ACE.2 are equal. It is possible that this statistic was not recorded for that particular match.

In [95]:
# print the NaNs for the Aces
ace1_nan = gs_matches['ACE.1'].isna()
ace2_nan = gs_matches['ACE.2'].isna()
ace_nan = np.logical_or(ace1_nan,ace2_nan)

gs_matches[ace_nan]

,Player1,Player2,Round,Result,FNL.1,FNL.2,FSP.1,FSW.1,SSP.1,SSW.1,...,NPA.2,NPW.2,TPW.2,ST1.2,ST2.2,ST3.2,ST4.2,ST5.2,Gender,GrandSlam
132,Sachia Vickery,Lauren Davis,1,0,0.0,2.0,51,14,49,12,...,7.0,12.0,63.0,6.0,6.0,NaN,NaN,NaN,women,AusOpen
172,Lourdes Dominguez Lino,Caroline Wozniacki,1,0,0.0,2.0,58,10,42,8,...,11.0,18.0,58.0,6.0,6.0,NaN,NaN,NaN,women,AusOpen
211,Bojana Jovanovski,Yvonne Meusburger,2,0,1.0,2.0,69,30,31,14,...,9.0,12.0,92.0,3.0,6.0,6.0,NaN,NaN,women,AusOpen
224,Alize Cornet,Maria Sharapova,3,0,0.0,2.0,65,24,35,9,...,12.0,13.0,81.0,6.0,7.0,NaN,NaN,NaN,women,AusOpen
228,Yvonne Meusburger,Victoria Azarenka,3,0,0.0,2.0,70,8,30,4,...,14.0,17.0,56.0,6.0,6.0,NaN,NaN,NaN,women,AusOpen
365,Karin Knapp,Sloane Stephens,1,0,0.0,2.0,57,18,43,13,...,1.0,4.0,61.0,6.0,7.0,NaN,NaN,NaN,women,FrenchOpen
366,Vania King,Alexandra Cadantu,1,1,2.0,0.0,74,27,26,11,...,5.0,9.0,64.0,6.0,1.0,NaN,NaN,NaN,women,FrenchOpen
379,Irina-Camelia Begu,Silvia Soler-Espinosa,1,0,0.0,2.0,74,26,26,6,...,4.0,6.0,71.0,6.0,6.0,NaN,NaN,NaN,women,FrenchOpen
380,Alize Cornet,Maria Joao Koehler,1,1,2.0,0.0,70,28,30,11,...,4.0,8.0,58.0,5.0,2.0,NaN,NaN,NaN,women,FrenchOpen
392,Na Li,A. Medina Garrigues,1,1,2.0,0.0,71,31,29,7,...,1.0,1.0,57.0,3.0,4.0,NaN,NaN,NaN,women,FrenchOpen
393,Arantxa Rus,Sara Errani,1,0,0.0,2.0,52,11,48,2,...,3.0,7.0,52.0,6.0,6.0,NaN,NaN,NaN,women,FrenchOpen
402,Chanelle Scheepers,Mathilde Johansson,1,0,0.0,2.0,54,16,46,13,...,6.0,9.0,72.0,7.0,6.0,NaN,NaN,NaN,women,FrenchOpen
405,Urszula Radwanska,Venus Williams,1,1,2.0,1.0,68,48,32,16,...,30.0,47.0,121.0,6.0,7.0,4.0,NaN,NaN,women,FrenchOpen
419,Petra Cetkovska,Olga Puchkova,1,1,2.0,0.0,69,25,31,8,...,0.0,0.0,32.0,0.0,2.0,NaN,NaN,NaN,women,FrenchOpen
422,Monica Niculescu,Johanna Larsson,1,0,0.0,2.0,82,15,18,4,...,12.0,14.0,61.0,6.0,6.0,NaN,NaN,NaN,women,FrenchOpen
439,Yulia Putintseva,Sara Errani,2,0,0.0,2.0,64,11,36,5,...,9.0,11.0,59.0,6.0,6.0,NaN,NaN,NaN,women,FrenchOpen
443,Mathilde Johansson,Ana Ivanovic,2,0,0.0,2.0,73,17,27,4,...,2.0,2.0,58.0,6.0,6.0,NaN,NaN,NaN,women,FrenchOpen
475,Carla Suarez Navarro,Sara Errani,4,0,1.0,2.0,67,32,33,14,...,14.0,24.0,107.0,5.0,6.0,6.0,NaN,NaN,women,FrenchOpen
609,C.Suarez Navarro,L.Dominguez Lino,1,1,2.0,0.0,68,27,32,14,...,22.0,14.0,NaN,2.0,2.0,NaN,NaN,NaN,women,Wimbledon
635,M.Torro-Flor,I.Begu,1,1,2.0,0.0,72,25,28,8,...,9.0,8.0,NaN,3.0,4.0,NaN,NaN,NaN,women,Wimbledon
655,O.Puchkova,A.Rus,1,1,2.0,0.0,69,24,31,4,...,9.0,6.0,NaN,4.0,2.0,NaN,NaN,NaN,women,Wimbledon
683,A.Radwanska,M.Johansson,2,1,2.0,0.0,62,23,38,12,...,27.0,18.0,NaN,1.0,3.0,NaN,NaN,NaN,women,Wimbledon

Our inference above is correct in that the missing values of ACE.1 and ACE.2 occur in the same match. We decided to impute by mean to fill in the missing values. According to the table below, all of the missing ACE values occur in women's matches across three Grand Slams. Typically, women do not hit as many aces as men, so it would not make sense to take men's aces statistics into consideration. Thus we differentiate by Gender and Grand Slam. The logic above is used for all imputations computed below.

In [96]:
# impute by the mean differentiating by Gender and Grand Slam
gs_matches["ACE.1"].fillna(gs_matches.groupby(["Gender", "GrandSlam"])["ACE.1"].transform("mean"), inplace=True)
gs_matches["ACE.2"].fillna(gs_matches.groupby(["Gender", "GrandSlam"])["ACE.2"].transform("mean"), inplace=True)

gs_matches[ace_nan][["ACE.1", "ACE.2"]]

        ACE.1     ACE.2
132  3.148760  2.694215
172  3.148760  2.694215
211  3.148760  2.694215
224  3.148760  2.694215
228  3.148760  2.694215
365  2.508929  1.794643
366  2.508929  1.794643
379  2.508929  1.794643
380  2.508929  1.794643
392  2.508929  1.794643
393  2.508929  1.794643
402  2.508929  1.794643
405  2.508929  1.794643
419  2.508929  1.794643
422  2.508929  1.794643
439  2.508929  1.794643
443  2.508929  1.794643
475  2.508929  1.794643
609  2.982906  3.299145
635  2.982906  3.299145
655  2.982906  3.299145
683  2.982906  3.299145

#### Double Faults NaN

The 6 instances of DBF.X occur in the same matches. There does not appear to be a single event where this statistic is missing, so we impute by mean.

In [109]:
# print NaNs for Double faults
dbf1_nan = gs_matches['DBF.1'].isna()
dbf2_nan = gs_matches['DBF.2'].isna()
dbf_nan = np.logical_or(dbf1_nan,dbf2_nan)

gs_matches[dbf_nan]

Empty DataFrame
Columns: [Result, FSP.1, FSW.1, SSP.1, SSW.1, ACE.1, DBF.1, WNR.1, UFE.1, BPC.1, BPW.1, NPA.1, NPW.1, FSP.2, FSW.2, SSP.2, SSW.2, ACE.2, DBF.2, WNR.2, UFE.2, BPC.2, BPW.2, NPA.2, NPW.2, Gender, GrandSlam]
Index: []

[0 rows x 27 columns]

In [98]:
# impute by the mean differentiating by Gender and Grand Slam
gs_matches['DBF.1'].fillna(gs_matches.groupby(["Gender", "GrandSlam"])["DBF.1"].transform("mean"), inplace=True)
gs_matches['DBF.2'].fillna(gs_matches.groupby(["Gender", "GrandSlam"])["DBF.2"].transform("mean"), inplace=True)

gs_matches[dbf_nan]

,Player1,Player2,Round,Result,FNL.1,FNL.2,FSP.1,FSW.1,SSP.1,SSW.1,...,NPA.2,NPW.2,TPW.2,ST1.2,ST2.2,ST3.2,ST4.2,ST5.2,Gender,GrandSlam
7,David Guez,Richard Gasquet,1,0,0.0,3.0,64,26,36,12,...,8.0,11.0,94.0,7.0,6.0,6.0,NaN,NaN,men,AusOpen
294,Simone Bolelli,Yen-Hsun Lu,1,0,0.0,3.0,63,33,37,12,...,4.0,6.0,78.0,6.0,6.0,2.0,NaN,NaN,men,FrenchOpen
300,Somdev Devvarman,Roger Federer,2,0,0.0,3.0,61,19,39,16,...,19.0,30.0,88.0,6.0,6.0,6.0,NaN,NaN,men,FrenchOpen
427,Vania King,Sloane Stephens,2,0,0.0,2.0,82,17,18,6,...,7.0,11.0,57.0,6.0,6.0,NaN,NaN,NaN,women,FrenchOpen
484,Serena Williams,Sara Errani,6,1,2.0,0.0,52,14,48,14,...,2.0,2.0,16.0,0.0,1.0,NaN,NaN,NaN,women,FrenchOpen
549,N.Djokovic,F.Mayer,1,1,3.0,0.0,63,41,37,26,...,29.0,19.0,NaN,3.0,5.0,4.0,NaN,NaN,men,Wimbledon

#### Winners and Unforced Errors NaN

In [99]:
# print NaNs for the Winners and Unforced errors
wnr1_nan = gs_matches['WNR.1'].isna()
wnr2_nan = gs_matches['WNR.2'].isna()
ufe1_nan = gs_matches['UFE.1'].isna()
ufe2_nan = gs_matches['UFE.2'].isna()
wnr_and_ufe_nan = np.logical_or.reduce([wnr1_nan,wnr2_nan,ufe1_nan,ufe2_nan])

gs_matches[wnr_and_ufe_nan]

,Player1,Player2,Round,Result,FNL.1,FNL.2,FSP.1,FSW.1,SSP.1,SSW.1,...,NPA.2,NPW.2,TPW.2,ST1.2,ST2.2,ST3.2,ST4.2,ST5.2,Gender,GrandSlam
719,Richard Gasquet,Michael Russell,1,1,3.0,0.0,63,45,37,16,...,30.0,40.0,83.0,3.0,4.0,2.0,NaN,NaN,men,USOpen
720,Stephane Robert,Albano Olivetti,1,1,3.0,0.0,61,44,39,19,...,NaN,NaN,71.0,3.0,3.0,4.0,NaN,NaN,men,USOpen
721,Jan-Lennard Struff,Guillaume Rufin,1,0,2.0,3.0,55,61,45,32,...,NaN,NaN,149.0,7.0,6.0,2.0,2.0,6.0,men,USOpen
722,Aljaz Bedene,Dmitry Tursunov,1,0,1.0,3.0,52,41,48,19,...,NaN,NaN,121.0,7.0,4.0,6.0,6.0,NaN,men,USOpen
723,Feliciano Lopez,Florent Serra,1,1,3.0,1.0,58,54,42,30,...,NaN,NaN,123.0,7.0,2.0,3.0,3.0,NaN,men,USOpen
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
837,Novak Djokovic,Mikhail Youzhny,1,1,3.0,1.0,68,49,32,19,...,10.0,21.0,87.0,3.0,2.0,6.0,0.0,NaN,men,USOpen
838,Andy Murray,Stanislas Wawrinka,1,0,0.0,3.0,63,37,37,22,...,31.0,42.0,107.0,6.0,6.0,6.0,NaN,NaN,men,USOpen
839,Novak Djokovic,Stanislas Wawrinka,1,1,3.0,2.0,67,64,33,25,...,26.0,41.0,165.0,6.0,6.0,6.0,3.0,4.0,men,USOpen
840,Richard Gasquet,Rafael Nadal,1,0,0.0,3.0,64,41,36,15,...,22.0,28.0,102.0,6.0,7.0,6.0,NaN,NaN,men,USOpen
841,Novak Djokovic,Rafael Nadal,1,0,1.0,3.0,68,40,32,16,...,17.0,23.0,121.0,6.0,3.0,6.0,6.0,NaN,men,USOpen

In [100]:
len(gs_matches[wnr_and_ufe_nan].loc[(gs_matches["Gender"] == "men") & (gs_matches["GrandSlam"] == "USOpen")])

123

Based on the analysis above, it is clear that all 123 missing instances of Winners and Unforced Errors occur in the Men's US Open. It does not make sense to impute by mean like we have done above since an entire tournament's statistic is missing. After researching online, there is another dataset that contains match statistics for the 2013 US Open. The relevant information is broken into two datasets: one of matches and their corresponding IDs and another with the point by point statistics for each match labelled by match ID.

In [101]:
# create dataframe for match IDs
us_open_ids = pd.read_table("2013-usopen-matches.csv", sep=',', 
             usecols=['match_id','player1','player2'])
# create dataframe for point-by-point statistics, focusing on winners and unforced errors
us_open_matches = pd.read_table("2013-usopen-points.csv", sep=',', 
             usecols=['match_id','P1UnfErr','P2UnfErr','P1Winner','P2Winner'])

# sum statistics for each match
us_open_matches_grouped = us_open_matches.groupby('match_id').sum().reset_index()
# merge dataframes on match IDs
us_matches_found = pd.merge(us_open_ids,us_open_matches_grouped,on='match_id')

# rename columns to match with original dataframe to merge successfully
us_matches_found.rename(columns={'player1':'Player1','player2':'Player2',
                                 'P1Winner': 'WNR.1','P2Winner':'WNR.2',
                                 'P1UnfErr':'UFE.1', 'P2UnfErr': 'UFE.2'}, inplace=True)
del us_matches_found['match_id']
us_matches_found

                Player1             Player2  WNR.1  WNR.2  UFE.1  UFE.2
0        Novak Djokovic   Ricardas Berankis     28     16      9     27
1          Benoit Paire  Alex Bogomolov Jr.     86     39     68     41
2           Tim Smyczek     James Duckworth     32     24     39     71
3            Rajeev Ram       Fabio Fognini     24     25     18     31
4            Tommy Haas  Paul-Henri Mathieu     38     24     13     26
..                  ...                 ...    ...    ...    ...    ...
162       Roberta Vinci     Flavia Pennetta     14     23     28     17
163  Daniela Hantuchova   Victoria Azarenka     19     17     18     15
164     Serena Williams               Na Li     19      8     20     24
165     Flavia Pennetta   Victoria Azarenka     19     15     23     25
166     Serena Williams   Victoria Azarenka     36     17     35     27

[167 rows x 6 columns]

In [102]:
# subset of Men's US Open from original merged dataframe
old_us_open_men = gs_matches[(gs_matches["Gender"] == "men") & (gs_matches["GrandSlam"] == "USOpen")].copy()
# replace missing values with statistics from second dataset
# use player names to match
old_us_open_men = old_us_open_men.drop(["WNR.1","WNR.2","UFE.1","UFE.2"], axis=1)
new_us_open_men = pd.merge(old_us_open_men, us_matches_found,on=["Player1","Player2"], how="left")

# finding where Men's US Open starts in original dataframe
index = gs_matches[(gs_matches["Gender"] == "men") & (gs_matches["GrandSlam"] == "USOpen")].index[0]

# update with calculated match statistics
for i in range(len(new_us_open_men)):
    gs_matches.loc[index+i,"UFE.1"] = new_us_open_men.loc[i,"UFE.1"]
    gs_matches.loc[index+i,"UFE.2"] = new_us_open_men.loc[i,"UFE.2"]
    gs_matches.loc[index+i,"WNR.1"] = new_us_open_men.loc[i,"WNR.1"]
    gs_matches.loc[index+i,"WNR.2"] = new_us_open_men.loc[i,"WNR.2"]

# count how many missing values are left
gs_matches[(gs_matches["Gender"] == "men") & (gs_matches["GrandSlam"] == "USOpen")][["WNR.1","WNR.2","UFE.1","UFE.2"]].isna().sum()

WNR.1    37
WNR.2    37
UFE.1    37
UFE.2    37
dtype: int64

After we impute the data, we reduced the number of missing winners and unforced errors from 123 instances to 37. Now we can fill in the rest of the missing values like we have done above.

In [103]:
# impute remaining values by the mean differentiating by Gender and Grand Slam
gs_matches['UFE.1'].fillna(gs_matches.groupby(["Gender", "GrandSlam"])["UFE.1"].transform("mean"), inplace=True)
gs_matches['UFE.2'].fillna(gs_matches.groupby(["Gender", "GrandSlam"])["UFE.2"].transform("mean"), inplace=True)
gs_matches['WNR.1'].fillna(gs_matches.groupby(["Gender", "GrandSlam"])["WNR.1"].transform("mean"), inplace=True)
gs_matches['WNR.2'].fillna(gs_matches.groupby(["Gender", "GrandSlam"])["WNR.2"].transform("mean"), inplace=True)

#### Net Points NaN

There are 83 missing instances of net points attempted and 82 missing instances of net points won. There does not appear to be a single event where this statistic is missing, so we impute by mean.

In [104]:
# print NaNs for Net points attempted and won
npa1_nan = gs_matches['NPA.1'].isna()
npa2_nan = gs_matches['NPA.2'].isna()
npw1_nan = gs_matches['NPW.1'].isna()
npw2_nan = gs_matches['NPW.2'].isna()
npa_and_npw_nan = np.logical_or.reduce([npa1_nan,npa2_nan,npw1_nan,npw2_nan])

gs_matches[npa_and_npw_nan]

,Player1,Player2,Round,Result,FNL.1,FNL.2,FSP.1,FSW.1,SSP.1,SSW.1,...,NPA.2,NPW.2,TPW.2,ST1.2,ST2.2,ST3.2,ST4.2,ST5.2,Gender,GrandSlam
1,Leonardo Mayer,Albert Montanes,1,1,3.0,0.0,61,31,39,13,...,NaN,NaN,42.0,1.0,3.0,1.0,NaN,NaN,men,AusOpen
3,Dmitry Tursunov,Michael Russell,1,1,3.0,0.0,53,39,47,24,...,NaN,NaN,79.0,2.0,2.0,3.0,NaN,NaN,men,AusOpen
8,Nikolay Davydenko,Lukasz Kubot,1,1,3.0,2.0,77,76,23,11,...,NaN,NaN,141.0,6.0,3.0,6.0,3.0,4.0,men,AusOpen
13,Alejandro Falla,Mikhail Kukushkin,1,1,3.0,1.0,60,50,40,23,...,NaN,NaN,128.0,7.0,2.0,2.0,3.0,NaN,men,AusOpen
15,Steve Johnson,Adrian Mannarino,1,0,2.0,3.0,53,50,47,28,...,NaN,NaN,142.0,3.0,6.0,6.0,5.0,6.0,men,AusOpen
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
801,Alexandr Dolgopolov,Mikhail Youzhny,1,0,0.0,3.0,53,35,47,19,...,NaN,NaN,104.0,7.0,6.0,6.0,NaN,NaN,men,USOpen
802,Evgeny Donskoy,Peter Gojowczyk,1,1,3.0,2.0,55,63,45,34,...,NaN,NaN,151.0,3.0,4.0,6.0,6.0,3.0,men,USOpen
807,Tobias Kamke,Denis Istomin,1,0,0.0,3.0,46,19,54,23,...,NaN,NaN,82.0,6.0,6.0,6.0,NaN,NaN,men,USOpen
890,A Barty,A Pavlyuchenkova,2,0,0.0,2.0,52,13,48,10,...,NaN,NaN,NaN,6.0,6.0,NaN,NaN,NaN,women,USOpen
905,A.Radwanska,S.Soler-Espinosa,1,1,2.0,0.0,72,26,28,6,...,NaN,34.0,NaN,1.0,2.0,NaN,NaN,NaN,women,USOpen

In [105]:
# impute by the mean differentiating by Gender and Grand Slam
gs_matches['NPA.1'].fillna(gs_matches.groupby(["Gender", "GrandSlam"])["NPA.1"].transform("mean"), inplace=True)
gs_matches['NPA.2'].fillna(gs_matches.groupby(["Gender", "GrandSlam"])["NPA.2"].transform("mean"), inplace=True)
gs_matches['NPW.1'].fillna(gs_matches.groupby(["Gender", "GrandSlam"])["NPW.1"].transform("mean"), inplace=True)
gs_matches['NPW.2'].fillna(gs_matches.groupby(["Gender", "GrandSlam"])["NPW.2"].transform("mean"), inplace=True)

### Relevant Attributes

There are certain statistics in the dataset that give up information about who won the match. For example, "FNL.X" is the number of sets won by each player. Knowing how many sets a player has won tells us who won the match. Other statistics that also give us similiar information are "ST" (Set score) and "TPW" (Total points won). Since we want to determine how match statistics relate to the outcome of a match, these columns should be deleted. We also want to be able to generalize our results for all players and all matches of a Grand Slam, so "Player" and "Round" are not necessary.

In [106]:
# delete irrelevant columns
gs_matches.drop(list(gs_matches.filter(regex="(Player)|(Round)|(FNL)|(ST)|(TPW)")), axis = 1, inplace = True)

gs_matches

,Result,FSP.1,FSW.1,SSP.1,SSW.1,ACE.1,DBF.1,WNR.1,UFE.1,BPC.1,...,ACE.2,DBF.2,WNR.2,UFE.2,BPC.2,BPW.2,NPA.2,NPW.2,Gender,GrandSlam
0,0,61,35,39,18,5.0,1.0,17.0,29.0,1.0,...,10.0,0.0,40.0,30.0,4.0,8.0,8.000000,9.0000,men,AusOpen
1,1,61,31,39,13,13.0,1.0,13.0,1.0,7.0,...,1.0,4.0,1.0,4.0,0.0,0.0,16.947917,24.8125,men,AusOpen
2,0,52,53,48,20,8.0,4.0,37.0,50.0,1.0,...,9.0,1.0,41.0,41.0,4.0,13.0,12.000000,16.0000,men,AusOpen
3,1,53,39,47,24,8.0,6.0,8.0,6.0,6.0,...,1.0,8.0,1.0,8.0,1.0,7.0,16.947917,24.8125,men,AusOpen
4,0,76,63,24,12,0.0,4.0,16.0,35.0,3.0,...,17.0,11.0,59.0,79.0,3.0,5.0,16.000000,28.0000,men,AusOpen
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,1,59,32,41,10,2.0,5.0,24.0,35.0,13.0,...,0.0,3.0,14.0,43.0,9.0,4.0,14.000000,9.0000,women,USOpen
914,0,53,48,47,21,6.0,4.0,35.0,51.0,7.0,...,5.0,2.0,26.0,29.0,13.0,3.0,13.000000,10.0000,women,USOpen
915,0,49,17,51,4,3.0,7.0,20.0,31.0,0.0,...,0.0,1.0,11.0,6.0,8.0,5.0,6.000000,5.0000,women,USOpen
916,0,63,12,37,3,0.0,4.0,6.0,26.0,2.0,...,1.0,1.0,9.0,12.0,12.0,6.0,10.000000,8.0000,women,USOpen
917,1,51,29,49,15,8.0,1.0,49.0,41.0,25.0,...,1.0,2.0,21.0,29.0,13.0,4.0,14.000000,7.0000,women,USOpen

In [108]:
gs_matches.isna().sum()

Result       0
FSP.1        0
FSW.1        0
SSP.1        0
SSW.1        0
ACE.1        0
DBF.1        0
WNR.1        0
UFE.1        0
BPC.1        0
BPW.1        0
NPA.1        0
NPW.1        0
FSP.2        0
FSW.2        0
SSP.2        0
SSW.2        0
ACE.2        0
DBF.2        0
WNR.2        0
UFE.2        0
BPC.2        0
BPW.2        0
NPA.2        0
NPW.2        0
Gender       0
GrandSlam    0
dtype: int64

As a result of the data cleaning process, we do not have anymore missing values and are left with relevant match information, which will be used to predict match results.

## Exploratory Analysis & Data Visualization

## Analysis

## Conclusion